### ISSUE TITLE
[Bug]: Typo in check name

### ISSUE THREAD

**Issue by goldendevil1711** [mint-choc-chip-skyblade/sshd-rando#337]
### Discord ID / GitHub Username

goldendevil1711

### What did you expect to happen?

The check name "Faron Woods - Stamina Fruit after Kiwki in Clearing" has a typo - should be "Kikwi" not "Kiwki"

### What actually happened?

N/A, just a typo

### OS

Windows

### Platform

Console

### Randomizer Version

1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CovenEsme** [comment]
Fixed in #357 :p
