### ISSUE TITLE
[Bug]: Sparrot's Closet item did not spawn

### ISSUE THREAD

**Issue by goldendevil1711** [mint-choc-chip-skyblade/sshd-rando#339]
### Discord ID / GitHub Username

goldendevil1711

### What did you expect to happen?

When I went to check Sparrot's Closet, I expected to get an item. According to my 
[Spoiler Log](https://github.com/user-attachments/files/15751390/Kina.Gate.Scaldera.Spoiler.Log.txt) it should have been 5 Deku Seeds

### What actually happened?

I did not get any items. See clip: https://clips.twitch.tv/HomelyTentativeMarrowLitty-exLSXgKVz0YKOzYl

### OS

Windows

### Platform

Console

### Randomizer Version

1.0

### Relevant log output

```shell
Spoiler log is attached
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CovenEsme** [comment]
I've not quite figured out why this happens yet but it seems like you need to specifically collect the bonk check in Sparrot's room and then open the closet to get this bug. Even more specifically, reloading the room between collecting the bonked item and opening the closet prevents the bug?

Until I can find a fix for it, remember to open the closet before collecting the bonk check.

**Comment by CovenEsme** [comment]
Should be fixed with #359
