### ISSUE TITLE
[Bug]: Digging Robots not spawning items

### ISSUE THREAD

**Issue by goldendevil1711** [mint-choc-chip-skyblade/sshd-rando#341]
### Discord ID / GitHub Username

goldendevil1711

### What did you expect to happen?

I expected to get items from the Digging Robots in the Side Room and near the Mine Exit

### What actually happened?

I didn't get an item. [Here is the two robots in the side room](https://clips.twitch.tv/CloudyHomelyBananaAsianGlow-jvFikxqMkcIsen8j)

I also could not get [Digging Robot near Mine Exit](https://clips.twitch.tv/PluckyTangiblePepperOMGScoots-25Mk7YnD1U-yfAT9).

I was able to get the deactivated ones in the front of Mine after some very precise angle Gust Bellows usage, and easily got the one near the Last Timeshift Stone. This could just be angles, but I could not get these 3 to spawn an item despite multiple attempts.

[Kina Gate Scaldera Spoiler Log.txt](https://github.com/user-attachments/files/15752658/Kina.Gate.Scaldera.Spoiler.Log.txt)

### OS

Windows

### Platform

Console

### Randomizer Version

1.0

### Relevant log output

```shell
Spoiler log is attached
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CovenEsme** [comment]
OH, yeah, that's a check naming issue I think. I think you actually have to blow the wall that the robots are digging up against? ngl, I thought we'd renamed those checks but I guess not ^^'

**Comment by CovenEsme** [comment]
I've renamed the checks in #364. The names aren't amazing but this should resolve the confusion which led to this issue :p
