### ISSUE TITLE
[Bug]: Fire Node - Bonk Power Supply not working

### ISSUE THREAD

**Issue by goldendevil1711** [mint-choc-chip-skyblade/sshd-rando#342]
### Discord ID / GitHub Username

goldendevil1711

### What did you expect to happen?

I expected an item to spawn

### What actually happened?

First entry into Fire Node, couldn't get an item. Video [here](https://www.twitch.tv/videos/2166821071?t=04h02m38s)

This is my second entry into Fire Node (I previously had no Bomb Bag). Same issue [here](https://clips.twitch.tv/BelovedHotNarwhalCopyThis-DNGQ8JQxRqmC8OFh).

Spoiler log attached.
[Kina Gate Scaldera Spoiler Log.txt](https://github.com/user-attachments/files/15752713/Kina.Gate.Scaldera.Spoiler.Log.txt)

### OS

Windows

### Platform

Console

### Randomizer Version

1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CovenEsme** [comment]
The target that you need to bonk is kinda really small. I think the original SS devs meant for you to need to bonk into the tiny iron bars after activating the power supply but also made it so you just can't bonk there??

You *can* still get those checks if you bonk it just right but the target should deffo be increased in size so you can just bonk anywhere on the power supply. Nice catch :p

**Comment by goldendevil1711** [comment]
Looking at the tracker and logic files, it appears that the logic expects you to be able to get the check before activating the power supply.

The Power Supply in Lightning Node was very easy to bonk. This one is very difficult.

**Comment by CovenEsme** [comment]
Yeah, I'm just speculating about what the original SS devs intended. Since you can bonk them without activating the power supplies in vanilla (even if it's a bit finicky), the logic reflects this. I'll make a change to increase the sizes so they cover the whole of the power supplies

**Comment by CovenEsme** [comment]
Fixed with #368 :p
