### ISSUE TITLE
[Suggestion]: Goddess Harp text - indicate that you have to press X to play it

### ISSUE THREAD

**Issue by goldendevil1711** [mint-choc-chip-skyblade/sshd-rando#343]
### Discord ID / GitHub Username

goldendevil1711

### What is your idea?

The tooltip text for Goddess Harp should have some indication that you need to press the X button to play it. It won't be a total failsafe, but it's better than nothing, since as far as I can tell, there's no indicator anywhere else in the game telling you how to play it.

### Idea Consent

- [X] I consent to allowing the randomizer devs to use my idea, modify it, or reject it at their discretion.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CovenEsme** [comment]
Resolved with #366 :p
