### ISSUE TITLE
[Suggestion]: Make all shields available from the start

### ISSUE THREAD

**Issue by goldendevil1711** [mint-choc-chip-skyblade/sshd-rando#345]
### Discord ID / GitHub Username

goldendevil1711

### What is your idea?

I noticed this because my Hylian shield got destroyed very early on by traps. At the start of a seed, at least my Allsanity, I could only buy the Wooden Shield. I believe that the Iron Shield only became available after I completed Skyloft. The Sacred Shield never became available at any point (likely because it is tied to defeating the Imprisoned, which never happens in randomizer). It would be great if the shield purchase requirements became decoupled from any dungeon requirements so that someone is able to buy one at any time, if their shield is destroyed or they do not start with one and want to buy one.

### Idea Consent

- [X] I consent to allowing the randomizer devs to use my idea, modify it, or reject it at their discretion.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gymnast86** [comment]
This has been implemented as of #404
