### ISSUE TITLE
[Bug]: Closed Thunderhead not available when getting required items.

### ISSUE THREAD

**Issue by Linoex-hash** [mint-choc-chip-skyblade/sshd-rando#365]
### Discord ID / GitHub Username

Linoex-hash 

### What did you expect to happen?

When Closed Thunderhead is selected, getting the Goddess Harp and Ballad of the Goddess should open the Thunderhead Dome no matter when I get them, independent of the other items I have in my inventory.

### What actually happened?

Thunderhead dome did not open when getting the necessary items: 

Item List:
![image](https://github.com/mint-choc-chip-skyblade/sshd-rando/assets/55114795/fbb85711-1e0a-4651-a281-ac231b4a56da)

Gameplay with first windmill circled. You can see the mirror is not facing the right way, but the windmill is:
![image](https://github.com/mint-choc-chip-skyblade/sshd-rando/assets/55114795/c13afcea-695b-4ec8-8a40-1beb8cdfdd51)

Gameplay with second windmill circled. You can see this windmill is oriented correctly as well:
![image](https://github.com/mint-choc-chip-skyblade/sshd-rando/assets/55114795/24a0f195-629f-4a1e-aeee-187243250f89)

Something that may be helpful is that the Skyloft tears trial is unlocked:
![image](https://github.com/mint-choc-chip-skyblade/sshd-rando/assets/55114795/fb645197-e643-4dc2-96ac-4a86d59648bf)

### OS

Windows

### Platform

Emulator

### Randomizer Version

1.0

### Relevant log output

```shell
Skyward Sword HD Randomizer Version: 1.0
Seed: 6VdLdSBHYDxnn@hHz3Y8
Setting String: U1NIRFItMS4wADEANlZkTGRTQkhZRHhubkBoSHozWTgAOleIAFAAuhpGbmgRJAAoUEAAJiMAkBEAFBBBABQAAAAAAAAAAAAAAgKAAAAgAAAAQAAAAACAAwAD0AEABAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJIgAACgAAAEEAAD8gbYt
Hash: Pipit Faron Tadtone
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CovenEsme** [comment]
Had you placed the Stone of Trials to open the Sky Keep dungeon entrance before trying to open The Thunderhead?

**Comment by Linoex-hash** [comment]
> Had you placed the Stone of Trials to open the Sky Keep dungeon entrance before trying to open The Thunderhead?

Yes

**Comment by CovenEsme** [comment]
Yeah, this is a known bug with the v1.0 release. Placing the Stone of Trials changes which Skyloft layer is being used. That layer didn't have the actor which detects harp playing on top of the light tower. #353 fixed this issue but we haven't created a v1.1 release yet. We will likely create a new release in the next couple of days

**Comment by Linoex-hash** [comment]
> Yeah, this is a known bug with the v1.0 release. Placing the Stone of Trials changes which Skyloft layer is being used. That layer didn't have the actor which detects harp playing on top of the light tower. #353 fixed this issue but we haven't created a v1.1 release yet. We will likely create a new release in the next couple of days

Aight solid, thanks for clarifying. Will I be able to update this rando playthrough once the new version is released? I should be able to use the existing seed right and settings right?

**Comment by CovenEsme** [comment]
Unfortunately, you won't be able to recreate the same seed when v1.1 is released. We have fixed several logical bugs which means that using the same settings + seed will result in different item placements

**Comment by Linoex-hash** [comment]
Gotcha, that's a little disappointing to hear, but understandable 😔 . I'll consider this seed beaten because I exhausted all locations that have progression items. Thunderhead is the most likely place to have the piece of the darn Triforce!

Thanks for responding quickly to my issue, I had no idea this bug was known and fixed before I even mentioned it.
