### ISSUE TITLE
[Bug]: Gratitude Crystals did not collect

### ISSUE THREAD

**Issue by goldendevil1711** [mint-choc-chip-skyblade/sshd-rando#379]
### Discord ID / GitHub Username

goldendevil1711

### What did you expect to happen?

I expected to get a 5 pack of Gratitude Crystals in the Second Rupee in Crawlspace before Spike Maze. Spoiler log attached.
[Rock Plaza Teller Spoiler Log.txt](https://github.com/user-attachments/files/15847788/Rock.Plaza.Teller.Spoiler.Log.txt)

### What actually happened?

No idea was given. See clip: https://clips.twitch.tv/RespectfulIcyYakBudStar-vZ7XPPMVaCHXKX3s

### OS

Windows

### Platform

Console

### Randomizer Version

1.0

### Relevant log output

```shell
Spoiler log is attached.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by goldendevil1711** [comment]
Okay. So I did get the item, but it did not get to me until I left the Spike Maze room entirely.

https://clips.twitch.tv/BrightAmazingKumquatBudStar-TQSl2KNjqVfB_pGw

**Comment by CovenEsme** [comment]
Yeah, this is due to a stupid thing with how that crawlspace works. You'll only get the item when you return to the main room.

Those 2 rupee checks are "advanced rupees" because of this weird behaviour. It's on my list of things to re-visit and figure out - I just haven't gotten round to it yet :p

**Comment by goldendevil1711** [comment]
Gym came in my chat and explained the issue. Sorry for bothering y'all.
